### ISSUE TITLE
When to release the full version code

### ISSUE THREAD

**Issue by xuankuzcr** [ZikangYuan/SDV-LOAM#7]
Dear author, 
Thank you for your contributions to open-source. I would like to inquire about when you will release the full version of this open-source code. I am in urgent need to perform comparison experiments with your work. Could you please provide your contact information?

**Comment by ZikangYuan** [comment]
Hello, due to the upgrading of the laboratory computers and the lack of good code storage habits before, the final version of this code was lost. We now have only partial module code, but not the full version code. The open sourced vision module is a version we reproduce according to the previous rest code. But we do not plan to reproduce the LiDAR module at this stage. Because we think that the cascaded framework like **V-LOAM** and **SDV-LOAM** is outdated, thus the reproduction doesn't make sense. In my opinion, **R3LIVE++** is the mainstream way of fusing vision and LiDAR. Later we will directly emulate **R3LIVE++** framework to make a set of our own code.

We apologize for the inconvenience to you.
